import { command, resolveSeasonIndexes } from './helpers.js';
export function registerSeasons(registry) {
  command(registry, { name: 'seasons.get', category: 'seasons', description: 'Obtiene temporadas.', usage: 'careerEditor.seasons.get(3)', execute: ({ stateManager }, selector = 'all') => { const state = stateManager.get(); return resolveSeasonIndexes(state, selector).map(i => structuredClone(state.seasons[i])); } });
  command(registry, { name: 'seasons.edit', category: 'seasons', description: 'Edita temporadas.', usage: 'careerEditor.seasons.edit(3,{...})', aliases: ['season'], execute: ({ stateManager, validator }, selector, patch) => { validator.patch(patch, 'temporada'); return stateManager.mutate('Temporada actualizada', draft => { for (const i of resolveSeasonIndexes(draft, selector)) draft.seasons[i] = { ...draft.seasons[i], ...structuredClone(patch), stats: patch.stats ? { ...draft.seasons[i].stats, ...patch.stats } : draft.seasons[i].stats }; }); } });
  command(registry, { name: 'seasons.last', category: 'seasons', description: 'Obtiene o edita la última.', usage: 'careerEditor.seasons.last({...})', aliases: ['lastSeason'], execute: (ctx, patch) => patch === undefined ? ctx.registry.get('seasons.get').execute(ctx, 'last')[0] : ctx.registry.get('seasons.edit').execute(ctx, 'last', patch) });
  command(registry, { name: 'seasons.all', category: 'seasons', description: 'Edita todas.', usage: 'careerEditor.allSeasons({...})', aliases: ['allSeasons'], execute: (ctx, patch) => ctx.registry.get('seasons.edit').execute(ctx, 'all', patch) });
  command(registry, { name: 'seasons.table', category: 'seasons', description: 'Tabla de temporadas.', usage: 'careerEditor.seasons.table()', execute: ({ stateManager }) => { const rows = stateManager.get().seasons.map((s, i) => ({ season: i + 1, age: s.age, team: s.teamId, overall: s.overall, marketValue: s.marketValue, appearances: s.stats?.appearances ?? 0, goals: s.stats?.goals ?? 0, assists: s.stats?.assists ?? 0, trophies: s.trophies?.length ?? 0, awards: s.awards?.length ?? 0 })); console.table(rows); return rows; } });
  command(registry, { name: 'seasons.compare', category: 'seasons', description: 'Compara temporadas.', usage: 'careerEditor.seasons.compare(3,5)', execute: (ctx, a, b) => { const rows = [a, b].map(x => ctx.registry.get('seasons.get').execute(ctx, x)[0]); console.table(rows); return rows; } });
}
