import { command, recalculateTotals, resolveSeasonIndexes } from './helpers.js';
const keys = ['appearances', 'goals', 'assists', 'cleanSheets', 'goalsConceded', 'trophies', 'awards'];
function normalized(patch, validator) { validator.patch(patch, 'estadísticas'); return Object.fromEntries(Object.entries(patch).map(([k, v]) => { if (!keys.includes(k)) throw new Error(`Estadística desconocida: ${k}.`); return [k, validator.number(v, k, { integer: true, min: 0 })]; })); }
export function registerStats(registry) {
  command(registry, { name: 'stats.get', category: 'stats', description: 'Obtiene totales.', usage: 'careerEditor.stats.get()', execute: ({ stateManager }) => structuredClone(stateManager.get().totals) });
  command(registry, { name: 'stats.set', category: 'stats', description: 'Reemplaza totales indicados.', usage: 'careerEditor.stats.set({...})', aliases: ['totals'], execute: ({ stateManager, validator }, patch) => stateManager.mutate('Totales actualizados', d => { d.totals = { ...d.totals, ...normalized(patch, validator) }; }) });
  command(registry, { name: 'stats.add', category: 'stats', description: 'Suma a totales.', usage: 'careerEditor.stats.add({...})', execute: ({ stateManager, validator }, patch) => stateManager.mutate('Totales incrementados', d => { for (const [k, v] of Object.entries(normalized(patch, validator))) d.totals[k] = (Number(d.totals[k]) || 0) + v; }) });
  command(registry, { name: 'stats.addLastSeason', category: 'stats', description: 'Suma estadísticas a la última temporada y sincroniza totales.', usage: 'careerEditor.stats.addLastSeason({goals:1})', execute: ({ stateManager, validator }, patch) => { const additions = normalized(patch, validator); for (const key of Object.keys(additions)) if (!['appearances', 'goals', 'assists', 'cleanSheets', 'goalsConceded'].includes(key)) throw new Error(`No se puede incrementar ${key} como estadística de temporada.`); return stateManager.mutate('Estadísticas de temporada incrementadas', draft => { const [index] = resolveSeasonIndexes(draft, 'last'), stats = draft.seasons[index].stats ??= {}; for (const [key, value] of Object.entries(additions)) stats[key] = (Number(stats[key]) || 0) + value; draft.totals = recalculateTotals(draft); }); } });
  command(registry, { name: 'stats.recalculate', category: 'stats', description: 'Recalcula desde temporadas.', usage: 'careerEditor.stats.recalculate()', aliases: ['recalculateTotals'], execute: ({ stateManager }) => stateManager.mutate('Totales recalculados', d => { d.totals = recalculateTotals(d); }) });
  command(registry, { name: 'stats.lastSeason', category: 'stats', description: 'Edita estadísticas de última temporada.', usage: 'careerEditor.stats.lastSeason({...})', execute: (ctx, patch) => ctx.registry.get('seasons.edit').execute(ctx, 'last', { stats: normalized(patch, ctx.validator) }) });
}
