import { command } from './helpers.js';
import { getAtPath } from '../core/paths.js';
export function registerWatcher(registry) {
  command(registry, { name: 'watch', category: 'runtime', description: 'Observa cambios.', usage: 'careerEditor.watch()', execute: ({ runtime, stateManager, logger }, ms = 1000) => { clearInterval(runtime.watcherTimer); let prior = JSON.stringify(stateManager.get()); runtime.watcherTimer = setInterval(() => { try { const next = JSON.stringify(stateManager.get()); if (next !== prior) logger.info('Cambio detectado'); prior = next; } catch {} }, Math.max(250, Number(ms))); return true; } });
  command(registry, { name: 'unwatch', category: 'runtime', description: 'Detiene watcher.', usage: 'careerEditor.unwatch()', execute: ({ runtime }) => { clearInterval(runtime.watcherTimer); runtime.watcherTimer = null; return true; } });
  command(registry, { name: 'freeze', category: 'runtime', description: 'Congela ruta.', usage: 'careerEditor.freeze("player.overall",99)', execute: ({ runtime, stateManager, validator }, path, value) => { validator.path(path); if (runtime.freezes.has(path)) clearInterval(runtime.freezes.get(path)); runtime.freezes.set(path, setInterval(() => { try { if (getAtPath(stateManager.get(), path, validator) !== value) stateManager.mutate(`Freeze ${path}`, d => { const parts = validator.path(path); let c = d; for (const k of parts.slice(0,-1)) c = c[k]; c[parts.at(-1)] = structuredClone(value); }); } catch {} }, 1000)); return true; } });
  command(registry, { name: 'unfreeze', category: 'runtime', description: 'Descongela ruta.', usage: 'careerEditor.unfreeze(path)', execute: ({ runtime }, path) => { clearInterval(runtime.freezes.get(path)); return runtime.freezes.delete(path); } });
  command(registry, { name: 'unfreezeAll', category: 'runtime', description: 'Detiene freezes.', usage: 'careerEditor.unfreezeAll()', execute: ({ runtime }) => { for (const timer of runtime.freezes.values()) clearInterval(timer); runtime.freezes.clear(); return true; } });
}
