import { PANEL_CSS } from './styles.js';

export function closeClubPicker(context){context.runtime.clubPanelHost?.remove();context.runtime.clubPanelHost=null;}
export function openClubPicker(context,api,catalog){
  closeClubPicker(context);const host=document.createElement('div'),root=host.attachShadow({mode:'open'});
  root.innerHTML=`<style>${PANEL_CSS}</style><section class="cee-shell" role="dialog" aria-label="Selector de clubes"><header class="cee-header"><div class="cee-mark">C</div><div class="cee-brand"><strong>SELECTOR DE CLUBES</strong><span>Catálogo verificado</span></div><button class="cee-icon-btn" data-close>×</button></header><main class="cee-body"><p class="cee-kicker">Mercado de pases</p><h2 class="cee-title">Elige tu próximo club.</h2><p class="cee-subtitle">Prepararemos una opción compatible para que la confirmes desde la interfaz original.</p><div class="cee-search"><input class="cee-input" placeholder="Buscar por nombre o ID…" autocomplete="off"></div><label class="cee-field"><span>Estrategia</span><select class="cee-select"><option value="replace">Reemplazar la oferta 1</option><option value="add">Añadir una oferta nueva</option></select></label><div class="cee-section-title"><span>Resultados</span><span class="cee-count"></span></div><div class="cee-list cee-results"></div><div class="cee-message"></div></main><footer class="cee-footer"><i class="cee-dot"></i><span>Solo clubes verificados</span><span class="cee-spacer"></span><code>${context.config.prefix}</code></footer></section>`;
  const input=root.querySelector('input'),results=root.querySelector('.cee-results'),message=root.querySelector('.cee-message'),count=root.querySelector('.cee-count');
  const showMessage=(value,error=false)=>{message.textContent=value;message.style.color=error?'var(--red)':'var(--green)';};
  const render=()=>{try{catalog.refresh();const clubs=catalog.search(input.value);count.textContent=`${clubs.length}`;if(!clubs.length){results.innerHTML='<div class="cee-empty">No encontré clubes verificados con esa búsqueda.</div>';return;}results.replaceChildren(...clubs.slice(0,50).map(club=>{const row=document.createElement('button');row.className='cee-row cee-club-row';row.type='button';const logo=document.createElement('span');logo.className='cee-logo';if(club.logo_url){const img=document.createElement('img');img.src=club.logo_url;img.alt='';logo.append(img);}else logo.textContent=String(club.name??club.id).slice(0,2).toUpperCase();const body=document.createElement('span');body.className='cee-row-main';const title=document.createElement('strong');title.textContent=club.name??club.id;const detail=document.createElement('span');detail.textContent=`${club.id} · ${club.country??club.country_fifa_code??'País desconocido'} · División ${club.division??club.divisionLevel??'?'}`;body.append(title,detail);const rep=document.createElement('span');rep.className='cee-pill';rep.textContent=`REP ${club.reputation??club.international_reputation??'?'}`;row.append(logo,body,rep);row.onclick=()=>{const before=context.runtime.lastError;const result=api.clubs.choose(club.id,{strategy:root.querySelector('select').value});if(result===undefined&&context.runtime.lastError!==before)showMessage(context.runtime.lastError.message,true);else showMessage(`Oferta de ${club.name??club.id} preparada. Ahora púlsala en el juego.`);};return row;}));}catch(error){results.innerHTML='<div class="cee-empty">No se pudo cargar el catálogo.</div>';showMessage(error.message,true);}};
  input.oninput=render;root.querySelector('[data-close]').onclick=()=>closeClubPicker(context);document.documentElement.append(host);context.runtime.clubPanelHost=host;render();input.focus();return host;
}
