import { PANEL_CSS } from './styles.js';

const money = value => { try { return new Intl.NumberFormat('es-ES',{notation:'compact',style:'currency',currency:'EUR',maximumFractionDigits:1}).format(Number(value)||0); } catch { return String(value ?? 0); } };
const text = value => value == null || value === '' ? '—' : String(value);
const html = value => text(value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));

function enableDrag(host, handle) {
  let drag = null;
  handle.addEventListener('pointerdown', event => {
    if (event.target.closest('button')) return;
    const rect = host.getBoundingClientRect(); drag = { x:event.clientX-rect.left, y:event.clientY-rect.top }; handle.setPointerCapture(event.pointerId);
  });
  handle.addEventListener('pointermove', event => { if (!drag) return; host.style.left=`${Math.max(6,Math.min(innerWidth-host.offsetWidth-6,event.clientX-drag.x))}px`; host.style.top=`${Math.max(6,Math.min(innerHeight-host.offsetHeight-6,event.clientY-drag.y))}px`; host.style.right='auto'; });
  handle.addEventListener('pointerup', () => { drag=null; });
}

export function openPanel(context, api) {
  closePanel(context);
  const host=document.createElement('div'),root=host.attachShadow({mode:'open'});
  root.innerHTML=`<style>${PANEL_CSS}</style><section class="cee-shell" role="dialog" aria-label="Copero Career Editor"><header class="cee-header"><div class="cee-mark">C</div><div class="cee-brand"><strong>COPERO CAREER EDITOR</strong><span>Career control · ${context.config.version}</span></div><button class="cee-icon-btn" data-action="compact" title="Modo compacto">—</button><button class="cee-icon-btn" data-action="refresh" title="Actualizar">↻</button><button class="cee-icon-btn" data-action="close" title="Cerrar">×</button></header><div class="cee-mini"><div class="cee-mini-card"><div class="cee-mini-ovr">—</div><div class="cee-mini-copy"><strong>Jugador</strong><span>Sin conexión</span></div><div class="cee-mini-stats"><div><span>PJ</span><strong>0</strong></div><div><span>GLS</span><strong>0</strong></div><div><span>AST</span><strong>0</strong></div></div></div></div><nav class="cee-tabs" aria-label="Secciones"><button class="cee-tab is-active" data-tab="overview">Resumen</button><button class="cee-tab" data-tab="player">Jugador</button><button class="cee-tab" data-tab="seasons">Carrera</button><button class="cee-tab" data-tab="backups">Backups</button></nav><main class="cee-body"><section class="cee-view" data-view="overview"></section><section class="cee-view" data-view="player" hidden></section><section class="cee-view" data-view="seasons" hidden></section><section class="cee-view" data-view="backups" hidden></section></main><div class="cee-toast"></div><footer class="cee-footer"><i class="cee-dot"></i><span>Conectado al simulador</span><span class="cee-spacer"></span><code class="cee-prefix"></code></footer></section>`;
  const shell=root.querySelector('.cee-shell'),toast=root.querySelector('.cee-toast'); let toastTimer;
  const notify=(message,error=false)=>{clearTimeout(toastTimer);toast.textContent=message;toast.className=`cee-toast is-visible${error?' is-error':''}`;toastTimer=setTimeout(()=>toast.className='cee-toast',2600);};
  const call=(label,action)=>{try{const result=action();if(result===undefined&&context.runtime.lastError)notify(context.runtime.lastError.message,true);else notify(label);render();return result;}catch(error){notify(error.message,true);}};
  const getState=()=>context.stateManager.get();
  const renderOverview=state=>{const p=state.player??{},last=state.seasons?.at(-1),totals=state.totals??{};root.querySelector('[data-view="overview"]').innerHTML=`<p class="cee-kicker">Partida conectada</p><div class="cee-hero"><div class="cee-player-line"><div><div class="cee-player-name"></div><div class="cee-club"></div></div><div class="cee-ovr"><span>OVR</span><strong>${html(p.overall)}</strong></div></div></div><div class="cee-statbar"><div class="cee-stat"><span>Edad</span><strong>${html(p.age)}</strong></div><div class="cee-stat"><span>PJ</span><strong>${Number(totals.appearances)||0}</strong></div><div class="cee-stat"><span>Gls</span><strong>${Number(totals.goals)||0}</strong></div><div class="cee-stat"><span>Ast</span><strong>${Number(totals.assists)||0}</strong></div><div class="cee-stat"><span>Valor</span><strong>${html(money(p.marketValue))}</strong></div></div><div class="cee-section-title">Acciones rápidas</div><div class="cee-actions"><button class="cee-button" data-quick="backup">＋ Backup</button><button class="cee-button secondary" data-quick="undo">↶ Deshacer</button><button class="cee-button secondary" data-quick="clubs">⌕ Mercado</button><button class="cee-button secondary" data-quick="help">? Comandos</button></div><div class="cee-section-title">Última temporada</div><div class="cee-row"><span class="cee-pill">${state.seasons?.length??0}</span><div class="cee-row-main"><strong>${html(last?.teamId??'Eligiendo club')}</strong><span>${last?`${Number(last.stats?.appearances)||0} PJ · ${Number(last.stats?.goals)||0} Gls · ${Number(last.stats?.assists)||0} Ast`:'La carrera está comenzando'}</span></div><span class="cee-pill">${html(last?.overall)} OVR</span></div>`;root.querySelector('.cee-player-name').textContent=p.lastName||'Libre';root.querySelector('.cee-club').textContent=`#${text(p.preferredNumber)} · ${text(p.position)} · ${text(p.currentTeamId??state.currentTeamId)}`;root.querySelector('.cee-mini-ovr').textContent=text(p.overall);root.querySelector('.cee-mini-copy strong').textContent=p.lastName||'Libre';root.querySelector('.cee-mini-copy span').textContent=`${text(p.position)} · ${text(p.currentTeamId??state.currentTeamId)}`;const mini=root.querySelectorAll('.cee-mini-stats strong');mini[0].textContent=Number(totals.appearances)||0;mini[1].textContent=Number(totals.goals)||0;mini[2].textContent=Number(totals.assists)||0;};
  const renderPlayer=state=>{const p=state.player??{};root.querySelector('[data-view="player"]').innerHTML=`<p class="cee-kicker">Editar jugador</p><h2 class="cee-title">Tu carrera, tus reglas.</h2><p class="cee-subtitle">Los cambios se validan y pueden deshacerse desde el historial.</p><div class="cee-form-grid"><label class="cee-field full"><span>Apellido mostrado</span><input class="cee-input" data-field="name" value=""></label><label class="cee-field"><span>Overall</span><input class="cee-input" data-field="overall" type="number" min="1" max="99" value="${p.overall??''}"></label><label class="cee-field"><span>Edad</span><input class="cee-input" data-field="age" type="number" min="0" value="${p.age??''}"></label><label class="cee-field"><span>Valor de mercado</span><input class="cee-input" data-field="price" type="number" min="0" value="${p.marketValue??''}"></label><label class="cee-field"><span>Dorsal</span><input class="cee-input" data-field="number" type="number" min="1" max="99" value="${p.preferredNumber??''}"></label><label class="cee-field"><span>Posición</span><input class="cee-input" data-field="position" value="${p.position??''}"></label><label class="cee-field"><span>Pie preferido</span><select class="cee-select" data-field="foot"><option value="right">Derecho</option><option value="left">Izquierdo</option></select></label></div><div class="cee-section-title">Aplicar cambios</div><button class="cee-button" data-save-player>Guardar jugador</button>`;root.querySelector('[data-field="name"]').value=p.lastName??'';root.querySelector('[data-field="foot"]').value=p.preferredFoot??'right';};
  const renderSeasons=state=>{const seasons=[...(state.seasons??[])].reverse();root.querySelector('[data-view="seasons"]').innerHTML=`<p class="cee-kicker">Historial</p><h2 class="cee-title">Temporadas</h2><p class="cee-subtitle">Un vistazo compacto a toda tu trayectoria.</p><div class="cee-list">${seasons.length?seasons.map((s,i)=>`<div class="cee-row"><span class="cee-pill">T${seasons.length-i}</span><div class="cee-row-main"><strong>${html(s.teamId)}</strong><span>${html(s.age)} años · ${Number(s.stats?.appearances)||0} PJ · ${Number(s.stats?.goals)||0} G · ${Number(s.stats?.assists)||0} A</span></div><span class="cee-pill">${html(s.overall)} OVR</span></div>`).join(''):'<div class="cee-empty">Todavía no hay temporadas terminadas.</div>'}</div>`;};
  const renderBackups=()=>{const backups=context.backupManager.list();root.querySelector('[data-view="backups"]').innerHTML=`<p class="cee-kicker">Puntos de restauración</p><h2 class="cee-title">Backups</h2><p class="cee-subtitle">Crea una copia antes de probar cambios grandes.</p><div class="cee-actions"><button class="cee-button" data-create-backup>＋ Crear backup</button><button class="cee-button secondary" data-redo>↷ Rehacer</button></div><div class="cee-section-title">Guardados en memoria</div><div class="cee-list">${backups.length?backups.map((b,i)=>`<div class="cee-row"><div class="cee-row-main"><strong></strong><span>${b.phase} · ${b.seasons} temporadas</span></div><button class="cee-icon-btn" data-restore="${i}" title="Restaurar">↺</button></div>`).join(''):'<div class="cee-empty">No hay backups disponibles.</div>'}</div>`;root.querySelectorAll('[data-restore]').forEach((button,i)=>{button.parentElement.querySelector('strong').textContent=backups[i].name;button.onclick=()=>call(`Backup ${backups[i].name} restaurado`,()=>api.restore(backups[i].name));});};
  const render=()=>{root.querySelector('.cee-prefix').textContent=context.config.prefix;try{const state=getState();renderOverview(state);renderPlayer(state);renderSeasons(state);renderBackups();bind();}catch(error){root.querySelector('[data-view="overview"]').innerHTML=`<div class="cee-empty"><strong>No pude conectar con la partida.</strong><br>${error.message}</div>`;notify(error.message,true);}};
  const bind=()=>{root.querySelector('[data-quick="backup"]')?.addEventListener('click',()=>call('Backup creado',()=>api.backup()));root.querySelector('[data-quick="undo"]')?.addEventListener('click',()=>call('Cambio deshecho',()=>api.undo()));root.querySelector('[data-quick="clubs"]')?.addEventListener('click',()=>api.clubs.panel());root.querySelector('[data-quick="help"]')?.addEventListener('click',()=>api.showHelp?api.showHelp():api.help);root.querySelector('[data-save-player]')?.addEventListener('click',()=>{const patch={};for(const input of root.querySelectorAll('[data-field]'))if(input.value!=='')patch[input.dataset.field]=input.type==='number'?Number(input.value):input.value;call('Jugador actualizado',()=>api.player(patch));});root.querySelector('[data-create-backup]')?.addEventListener('click',()=>call('Backup creado',()=>api.backup()));root.querySelector('[data-redo]')?.addEventListener('click',()=>call('Cambio rehecho',()=>api.redo()));};
  root.querySelectorAll('.cee-tab').forEach(tab=>tab.onclick=()=>{root.querySelectorAll('.cee-tab').forEach(x=>x.classList.toggle('is-active',x===tab));root.querySelectorAll('.cee-view').forEach(view=>view.hidden=view.dataset.view!==tab.dataset.tab);});
  root.querySelector('[data-action="close"]').onclick=()=>closePanel(context);root.querySelector('[data-action="refresh"]').onclick=()=>call('Panel actualizado',()=>true);root.querySelector('[data-action="compact"]').onclick=()=>{const compact=shell.classList.toggle('is-compact');root.querySelector('[data-action="compact"]').textContent=compact?'□':'—';root.querySelector('[data-action="compact"]').title=compact?'Expandir panel':'Modo compacto';};
  root.addEventListener('keydown',event=>{if(event.key==='Escape')closePanel(context);});
  document.documentElement.append(host);context.runtime.panelHost=host;enableDrag(shell,root.querySelector('.cee-header'));render();return host;
}

export function closePanel(context){context.runtime.panelHost?.remove();context.runtime.panelHost=null;}
