import { CONFIG, deriveGlobalName } from './config.js';
import { createRuntime } from './core/runtime.js'; import { Logger } from './core/logger.js'; import { Validator } from './core/validator.js'; import { ReactLocator } from './core/react-locator.js'; import { HistoryManager } from './core/history-manager.js'; import { BackupManager } from './core/backup-manager.js'; import { StateManager } from './core/state-manager.js'; import { CommandRegistry } from './core/command-registry.js'; import { CommandHandler } from './core/command-handler.js';
import { registerPlayer } from './modules/player.js'; import { registerSeasons } from './modules/seasons.js'; import { registerStats } from './modules/stats.js'; import { registerTrophies } from './modules/trophies.js'; import { ClubCatalog, registerClubs } from './modules/clubs.js'; import { registerImportExport } from './modules/import-export.js'; import { registerPresets } from './modules/presets.js'; import { registerWatcher } from './modules/watcher.js'; import { registerCore } from './modules/core-commands.js';
import { HelpRenderer } from './help/help-renderer.js'; import { openPanel, closePanel } from './ui/panel.js'; import { openClubPicker } from './ui/club-picker.js';

const globalName=deriveGlobalName(CONFIG); const old=window[globalName]; if(old?.__coperoCareerEditor) old.destroy?.({silent:true});
const runtime=createRuntime(), logger=new Logger(CONFIG), validator=new Validator(CONFIG), historyManager=new HistoryManager(CONFIG.maxHistoryEntries), locator=new ReactLocator(CONFIG,runtime), stateManager=new StateManager(locator,validator,historyManager,logger), backupManager=new BackupManager(stateManager), registry=new CommandRegistry(), catalog=new ClubCatalog(stateManager), help=new HelpRenderer(registry,CONFIG); let api;
const context={config:CONFIG,runtime,stateManager,historyManager,backupManager,validator,logger,registry}; const panels={open:ctx=>openPanel(ctx,api),close:closePanel};
registerPlayer(registry);registerSeasons(registry);registerStats(registry);registerTrophies(registry);registerClubs(registry,catalog);registerImportExport(registry);registerPresets(registry);registerWatcher(registry);registerCore(registry,help,panels);
const handler=new CommandHandler(registry,context); api={__coperoCareerEditor:true,version:CONFIG.version,prefix:CONFIG.prefix};
const namespaces={}; for(const c of registry.list()){const parts=c.name.split('.');if(parts.length===2){const [space,name]=parts;(namespaces[space]??={})[name]=(...args)=>handler.run(c.name,...args);}for(const alias of c.aliases)api[alias]=(...args)=>handler.run(alias,...args);if(parts.length===1)api[c.name]=(...args)=>handler.run(c.name,...args);}
for(const [space,methods] of Object.entries(namespaces)){if(typeof api[space]==='function')Object.assign(api[space],methods);else api[space]=methods;} api.backups={...api.backups,create:(...a)=>handler.run('backup',...a),restore:(...a)=>handler.run('restore',...a),remove:(...a)=>handler.run('deleteBackup',...a),list:()=>backupManager.list(),exists:n=>backupManager.exists(n)};
api.clubs.panel=()=>openClubPicker(context,api,catalog); api.destroy=({silent=false}={})=>{handler.run('unwatch');handler.run('unfreezeAll');closePanel(context);try{delete window[globalName];}catch{window[globalName]=undefined;}if(!silent)logger.success('Editor desinstalado.');return true;};
Object.defineProperties(api,{help:{enumerable:true,get(){return help.overview();}},status:{enumerable:true,get(){return handler.run('summary');}},get:{enumerable:true,get(){return handler.run('inspect');}}}); window[globalName]=api;
try{if(CONFIG.autoBackupOnInstall)backupManager.create('original');logger.success(`v${CONFIG.version} instalado. Usa ${CONFIG.prefix}help`);}catch(error){logger.warning('Editor instalado, pero no se creó backup original. Abre una partida y usa careerEditor.backup("original").',error.message);}
